---
- name: friendly debug
  when: lookup('env', 'LOCAL') != "true"
  debug:
    msg: "{{ jenkins_mode }}"

- name: download variables
  when: lookup('env', 'LOCAL') != "true"
  get_url:
    url: "https://raw.githubusercontent.com/{{ github_user }}/docker-{{ container_name }}/{{ github_branch }}/jenkins-vars.yml"
    dest: /tmp/jenkins-vars.yml

- name: include vars file for this project
  include_vars:
    file: "/tmp/jenkins-vars.yml"

- name: create destination dir for generated readme
  when: lookup('env', 'LOCAL') != "true"
  file:
    path: "{{ project_name }}"
    state: directory

- name: write jenkins file
  when:
    - lookup('env', 'LOCAL') != "true"
  template:
    src: ../templates/Jenkinsfile.j2
    dest: "{{ project_name }}/Jenkinsfile"
  delegate_to: localhost

- name: write jenkins file local
  when: lookup('env', 'LOCAL') == "true"
  template:
    src: ../templates/Jenkinsfile.j2
    dest: "/tmp/GENERATED.Jenkinsfile"
  delegate_to: localhost
