---

- name: download variables
  when: lookup('env', 'LOCAL') != "true"
  get_url:
    url: "https://raw.githubusercontent.com/{{ github_user }}/docker-{{ container_name }}/{{ github_branch }}/jenkins-vars.yml"
    dest: /tmp/jenkins-vars.yml

- name: include vars file for this project
  include_vars:
    file: "/tmp/jenkins-vars.yml"

- name: create destination dir for generated Jenkinsfile
  when: lookup('env', 'LOCAL') != "true"
  file:
    path: "jenkins/{{ project_name }}"
    state: directory

- name: create destination dir for generated FUNDING file
  when: lookup('env', 'LOCAL') == "true"
  file:
    path: "/tmp/.github"
    state: directory

- name: create destination dir for generated FUNDING file
  when: lookup('env', 'LOCAL') != "true"
  file:
    path: "jenkins/{{ project_name }}/.github"
    state: directory

- name: write jenkins file
  when:
    - lookup('env', 'LOCAL') != "true"
  template:
    src: ../templates/Jenkinsfile.j2
    dest: "jenkins/{{ project_name }}/Jenkinsfile"
  delegate_to: localhost

- name: write jenkins file local
  when: lookup('env', 'LOCAL') == "true"
  template:
    src: ../templates/Jenkinsfile.j2
    dest: "/tmp/GENERATED.Jenkinsfile"
  delegate_to: localhost

- name: write license file
  when:
    - lookup('env', 'LOCAL') != "true"
  template:
    src: ../templates/LICENSE.j2
    dest: "jenkins/{{ project_name }}/LICENSE"
  delegate_to: localhost

- name: write license file local
  when: lookup('env', 'LOCAL') == "true"
  template:
    src: ../templates/LICENSE.j2
    dest: "/tmp/LICENSE"
  delegate_to: localhost

- name: write funding file
  when:
    - lookup('env', 'LOCAL') != "true"
  template:
    src: ../templates/FUNDING.j2
    dest: "jenkins/{{ project_name }}/.github/FUNDING.yml"
  delegate_to: localhost

- name: write funding file local
  when: lookup('env', 'LOCAL') == "true"
  template:
    src: ../templates/FUNDING.j2
    dest: "/tmp/.github/FUNDING.yml"
  delegate_to: localhost

- name: Allow non root host to delete temp files
  when:
    - lookup('env', 'LOCAL') != "true"
  command: chmod -R 777 /ansible/jenkins
  delegate_to: localhost
