name: Package Trigger

on:
  schedule:
    - cron:  '04 0 * * 0'

jobs:
  package-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Package Trigger
        run: |
          curl -X POST \
            https://ci.linuxserver.io/job/Docker-Pipeline-Builders/job/docker-jenkins-builder/job/master/buildWithParameters?PACKAGE_CHECK=true \
            --user ${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }}
